version: "3"

services:
  dev:
    container_name: dev_web_muc_japan
    image: web_muc_japan-img-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "81:3000"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
